on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  reviung41:
    runs-on: ubuntu-latest
    name: reviung41

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        run: |
          sudo apt-get update
          sudo apt-get install git python3-pip dfu-util dfu-programmer avrdude
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/reviung/reviung41/keymaps
          ln -s $(pwd)/../reviung41 keyboards/reviung/reviung41/keymaps/ergenekonyigit
      - name: Build reviung41 firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb reviung41 -km ergenekonyigit
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: reviung41
          path: qmk_firmware/.build/reviung_reviung41_ergenekonyigit.hex

  corne:
    runs-on: ubuntu-latest
    name: corne

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        run: |
          sudo apt-get update
          sudo apt-get install git python3-pip dfu-util dfu-programmer avrdude
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/crkbd/keymaps
          ln -s $(pwd)/../corne keyboards/crkbd/keymaps/ergenekonyigit
      - name: Build corne firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb crkbd -km ergenekonyigit
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: corne
          path: qmk_firmware/.build/crkbd_rev1_ergenekonyigit.hex

  cantor:
    runs-on: ubuntu-latest
    name: cantor

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        run: |
          sudo apt-get update
          sudo apt-get install git python3-pip dfu-util dfu-programmer avrdude
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/cantor/keymaps
          ln -s $(pwd)/../cantor keyboards/cantor/keymaps/ergenekonyigit
      - name: Build cantor firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb cantor -km ergenekonyigit
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: cantor
          path: qmk_firmware/.build/cantor_ergenekonyigit.hex

  planck:
    runs-on: ubuntu-latest
    name: planck

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        run: |
          sudo apt-get update
          sudo apt-get install git python3-pip dfu-util dfu-programmer avrdude
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/handwired/glosso
          ln -s $(pwd)/../planck keyboards/handwired/glosso
      - name: Build planck firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb handwired/glosso -km default
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: planck
          path: qmk_firmware/.build/handwired_glosso_ergenekonyigit.hex

  gherkin:
    runs-on: ubuntu-latest
    name: gherkin

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        run: |
          sudo apt-get update
          sudo apt-get install git python3-pip dfu-util dfu-programmer avrdude
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/40percentclub/gherkin/keymaps
          ln -s $(pwd)/../gherkin keyboards/40percentclub/gherkin/keymaps/ergenekonyigit
      - name: Build gherkin firmware
        working-directory: ./qmk_firmware
        run: qmk compile -kb 40percentclub/gherkin -km ergenekonyigit
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: gherkin
          path: qmk_firmware/.build/40percentclub_gherkin_ergenekonyigit.hex
